apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::992382474575:role/FargatePodExecutionRole-arch-eks-02
      username: system:node:{{SessionName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::992382474575:role/RancherFargatePodExecutionRole-arch-eks-02
      username: system:node:{{SessionName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::992382474575:role/eks-arch-eks-02-nodeEksWorkers-1LL-RoleNodeInstance-DftOSQlbU9vJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::992382474575:role/eks-admin-Eliezer
      username: eks-admi
    - groups:      
      - system:masters
      rolearn: arn:aws:iam::992382474575:role/oidc-gitaction-role
      username: OidcGitActionRole
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  - system:node-proxier\n  rolearn: arn:aws:iam::992382474575:role/FargatePodExecutionRole-arch-eks-02\n  username: system:node:{{SessionName}}\n- groups:\n  - system:bootstrappers\n  - system:nodes\n  - system:node-proxier\n  rolearn: arn:aws:iam::992382474575:role/RancherFargatePodExecutionRole-arch-eks-02\n  username: system:node:{{SessionName}}\n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::992382474575:role/eks-arch-eks-02-nodeEksWorkers-1LL-RoleNodeInstance-DftOSQlbU9vJ\n  username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n  rolearn: arn:aws:iam::992382474575:role/eks-admin-Eliezer\n  username: eks-admi\n  - system:masters\n  rolearn: arn:aws:iam::992382474575:role/oidc-gitaction-role\n  username: OidcGitActionRole\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-02-05T19:05:22Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"175166800","uid":"8adbb0d8-b026-4bd6-8cb4-e844742eba94"}}
  creationTimestamp: "2024-02-05T19:05:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "226741063"
  uid: 8adbb0d8-b026-4bd6-8cb4-e844742eba94
